-- RideBack PostgreSQL schema
-- Create the database separately: CREATE DATABASE rideback;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(15) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(20) NOT NULL CHECK (role IN ('passenger', 'rider')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    availability VARCHAR(20) DEFAULT 'available' CHECK (availability IN ('available', 'busy', 'offline')),
    current_location VARCHAR(255),
    google_id VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    pickup_location VARCHAR(255) NOT NULL,
    drop_location VARCHAR(255) NOT NULL,
    passengers INTEGER DEFAULT 1,
    rider_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'ongoing', 'rejected', 'completed')),
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    distance_km NUMERIC(10,2),
    base_fare NUMERIC(10,2),
    discount NUMERIC(10,2) DEFAULT 0.00,
    final_fare NUMERIC(10,2),
    payment_status VARCHAR(20) DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed')),
    payment_method VARCHAR(20) CHECK (payment_method IN ('cash', 'online')),
    pickup_lat NUMERIC(10,7),
    pickup_lng NUMERIC(10,7),
    drop_lat NUMERIC(10,7),
    drop_lng NUMERIC(10,7),
    razorpay_order_id VARCHAR(255),
    razorpay_payment_id VARCHAR(255),
    razorpay_signature VARCHAR(255),
    paid_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_bookings_passenger_id ON bookings(passenger_id);
CREATE INDEX IF NOT EXISTS idx_bookings_rider_id ON bookings(rider_id);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
